### ISSUE TITLE
Export multiple layers (specified by name) at once

### ISSUE THREAD

**Issue by cknoll** [berteh/svg-objects-export#14]
For creating presentations with latex beamer it is very useful show complex graphics step by step. Usually I do this by creating the whole graphic in Inkscape, distribute the elements to different layers (say L1, ... L5) and then manually save a pdf copy for each "visibility-combination" that I want. (say L1 only; L1,L2; L1, L2, L3) and so on. Often I have to repeat this tedious process because I need to change some detail. I guess it should be possible to automate this with the svg-objects-export-script but I did not mange to specify the names of the layers which I want to export. Is that possible?

**Comment by berteh** [comment]
Hello cknoll.

Exporting all layers individually with a single command is explained in the [examples](https://github.com/berteh/svg-objects-export#examples).

There is currently no way to change the visibility of elements (i.e. export the same area with different combination of elements visible), but for the option to export each selected object separately (--extra " --export-id-only").

One option I'd consider would be to put linked copies (ald+d) of the elements of your backround slides in the foreground ones, so that each layer is actually a slide on its own... and since the copies are linked they updated automatically on modifications of the "source" layer.

hope this helps.

**Comment by berteh** [comment]
name of layers are stored in the attribute "inkscape:label", so to export a single layer by its name would be something like
```svg-objects-export --xpath "//svg:g[@inkscape:groupmode='layer'][@inkscape:label='layernamegoeshere']" -d destination/directory/ input.svg```


and to export all the layers called L1, L2, L3, L4,... in individual files in a single command you can use (for instance):  ```svg-objects-export --xpath "//svg:g[@inkscape:groupmode='layer'][re:test(@inkscape:label, 'L\d+', 'i')]" --extra " --export-area-page --export-id-only " -d destination/directory/ input.svg```

**Comment by berteh** [comment]
and this other tool seems to do exactly what you'd like: export groups of layers:
https://sites.google.com/site/rameyarnaud/media/images/inkscape-export-svg-layers-to-gif-animation

Since I don't plan on integrating this in svg-objects-export I close the issue report, feel free to re-open if you need more help... or to pull a code request that add such a feature in this script if you think it'd be a good addition.
