### ISSUE TITLE
Feature: export objects as svgs

### ISSUE THREAD

**Issue by Ramblurr** [berteh/svg-objects-export#4]
It would be great to export objects as SVG files, not just PNGs.

Edit: plain-svg doesn't work as expected. The resulting SVGs are not the individual objects, but rather the entire input SVG.

**Comment by a2retro** [comment]
Hi any idea when this might work?

**Comment by saulspatz** [comment]
If I understand the issue correctly, it has been fixed in Inkscape, after a fashion.  Adding the --export-id-only switch to the command line exports only the object with the given id.  Unfortunately it doesn't seem to give the exported object the correct y-coordinate, so that the icon does not display the drawing.  This can be fixed by finding the object in the GUI and changing the y-file coordinate to 0.  I've emailed the inkscape-dev list, offering to try to fix this if someone will confirm that it's a bug, but I haven't heard back.

**Comment by su-v** [comment]
@saulspatz - as mentioned in the comments of the original bug report referred to earlier: the incorrect placement is a known issue already tracked in a follow-up report (not fixed though):
* Bug #1306662 “[trunk: '-i -j' for plain SVG export fails to fit page size correctly (rev >= r13268)](https://bugs.launchpad.net/inkscape/+bug/1306662)”

**Comment by saulspatz** [comment]
I missed that, thanks.  I was trying to find it the other day, before I
wrote to the mailing list, but I just found old bugs about -i without -j.
Now I feel foolish.
I don't why no one's fixed it.  I know exactly what it's doing wrong.
 (Well, I'm very new to Inkscape and to SVG, so maybe there are more
complicated cases I don't know about.)

**Comment by berteh** [comment]
@saulspatz oh please, by any means, if you know how to fix this in inkscape, propose a patch to fix inkscape's bug [#1306662](https://bugs.launchpad.net/inkscape/+bug/1306662), that would be great... and wonderful for the use of this particular script as well ;)

You can find a few proposed "test" cases in this bug report, to check out if your idea of a solution works in this cases too.

Thanks!

**Comment by saulspatz** [comment]
@Berteh
I didn't know about the bug report when I wrote my email.  I need to make
sure I can build Inkscape, and then I'll take a shot at fixing the bug.
I'm really new to both Inkscape and SVG in general, so it may take me a
little while, but I'm definitely going to work on it.
